module.exports = [
    "last 2 versions",
    "not dead",
    "not ie > 0",
    "not op_mini all",
    "not baidu > 0",
    "not and_ff > 0",
    "not and_qq > 0",
    "not kaios > 0",
    "not op_mob > 0",
    "not ie_mob > 0",
    "not and_uc > 0",
    "not Samsung > 0",
    "not Android > 0",
];
